### PR TITLE
vheat fixes, other small fixes, auto low latency mod, update Readme

### PR DESCRIPTION
**Pull request by Benik3**
- CRC fix by vheat
- baudrate fix by vheat
- dump of message by vheat
- fix of speed and interval to prevent overflow
- destination folder is automaticaly created
- low latency mod is automaticaly enabled on serial (requires sudo)

### CODE REVIEW

**Review by alerighi — CHANGES_REQUESTED** [review]
Thanks for your improvements, I really appreciate them!

The only change I would suggest to make is to use Linux-specific code (i.e. setting the low latency mode ioctl and relative includes) under an `#ifdef __linux__` as I would like to maintain compatibility with non-Linux POSIX OS.

**Comment by Benik3** [comment]
Good point, I will fix it.

**Comment by Benik3** [comment]
@alerighi What do you use for building it on windows? I tried to build it using Cygwin64, but I had to comment out `tty.c_oflag &= ~OXTABS;` and `tty.c_oflag &= ~ONOEOT;`.
When I tried to run it, I found that I have to specify port in format \\\\.\COM1, but it failed then on _tcgetattr: Inappropriate ioctl_ for device

**Comment by alerighi** [comment]
I never tried to build on Windows, however it should build on the WSL version 1 (unfortunately version 2 doesn't currently passtrough serial ports), but I never tried it. 

However it should support any POSIX operating system, that is Linux, *BSD, macOS without issues. We can merge it as it is.

**Comment by Benik3** [comment]
ok, because what I found, it looks like windows use totally different system of work with COM ports...

**Pull request merged**
